import { Memory, Letter, Milestone, TimelineEvent, Place, FutureItem, VaultItem, LoveReason } from "./types";

export const MOCK_MEMORIES: Memory[] = [
  {
    id: "mem-1",
    title: "Temple Blessings & Golden Dusk in Chidambaram",
    description: "Walking hand in hand through the historic temple town of Chidambaram as lamps were lit and golden dusk settled over the peaceful streets.",
    date: "2024-05-02",
    media_url: "/images/tharani-surya-temple.jpg",
    media_type: "image",
    location: "Chidambaram, Tamil Nadu",
    category: "Trip",
    is_favorite: true,
    tags: ["Chidambaram", "Travel", "Temple", "Evening", "Peace"],
  },
  {
    id: "mem-2",
    title: "Marina Beach Walks & Coastal Breeze in Chennai",
    description: "Feet in the cool surf along the Chennai shoreline, watching evening city lights reflect on the gentle ocean waves while sharing roasted corn.",
    date: "2024-05-15",
    media_url: "/images/tharani-surya-candid.jpg",
    media_type: "image",
    location: "Chennai, Tamil Nadu",
    category: "Date Night",
    is_favorite: true,
    tags: ["Chennai", "Marina Beach", "Ocean", "Sunset", "Travel"],
  },
  {
    id: "mem-3",
    title: "First Date Road Trip: Karur to Trichy",
    description: "Our unforgettable first date on April 18, 2024. Singing along to songs on the highway, endless conversations, and falling in love.",
    date: "2024-04-18",
    media_url: "/images/our-first-date.jpg",
    media_type: "image",
    location: "Karur - Trichy, Tamil Nadu",
    category: "Milestone",
    is_favorite: true,
    tags: ["Karur", "Trichy", "First Date", "Road Trip", "Beginning"],
  },
  {
    id: "mem-4",
    title: "Playful Nights & Unstoppable Laughter",
    description: "Peeking behind your shoulder, sharing silly jokes and laughing under the night sky. True effortless happiness.",
    date: "2024-07-20",
    media_url: "/images/tharani-surya-playful.jpg",
    media_type: "image",
    location: "Tamil Nadu",
    category: "Quiet Moment",
    is_favorite: true,
    tags: ["Laughter", "Night", "Happiness", "Love"],
  },
  {
    id: "mem-5",
    title: "Spontaneous City Outing & Shopping Date",
    description: "Wandering through the aisles together, laughing over silly picks, and turning an ordinary shopping trip into our favorite date.",
    date: "2024-06-10",
    media_url: "/images/tharani-surya-shopping.jpg",
    media_type: "image",
    location: "Tamil Nadu",
    category: "Trip",
    is_favorite: true,
    tags: ["Shopping", "Date", "Fun", "Smiles"],
  },
  {
    id: "mem-6",
    title: "Traditional Elegance & Stolen Glances",
    description: "Dressed in traditional elegance, looking breathtaking and celebrating timeless moments together.",
    date: "2025-01-19",
    media_url: "/images/tharani-traditional-grace.jpg",
    media_type: "image",
    location: "Our Sanctuary",
    category: "Quiet Moment",
    is_favorite: false,
    tags: ["Traditional", "Grace", "Celebration", "Elegance"],
  },
];

export const MOCK_LETTERS: Letter[] = [
  {
    id: "let-1",
    title: "Open When You Miss Me",
    category: "Open when you miss me",
    content: `My love,

If the distance feels a little too wide tonight or the quiet in the room is too loud, close your eyes for a second. 

Remember the way my hand fits in yours—how naturally our fingers interlace, like two pieces of the same constellation finally aligning. No matter how many miles or hours lie between us, you carry my thoughts wherever you wander.

I left you a little voice recording attached to this letter. Play it, hear my breath, and remember that I am already counting down the seconds until I hold you again.

You are never alone. I am right here with you.`,
    author: "Tharani",
    recipient: "Surya",
    date: "2024-05-10",
    is_sealed: false,
    is_read: true,
    seal_color: "gold",
    image_url: "https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?auto=format&fit=crop&w=1200&q=80",
    image_caption: "Our quiet twilight walk along the pier, hands intertwined.",
    audio_url: "mock-audio-miss-you",
    audio_duration: "1:24",
  },
  {
    id: "let-2",
    title: "Open When You're Sad",
    category: "Open when you're sad",
    content: `Sweetheart,

If today was heavy, or a shadow has fallen over your spirit, please know this: you do not have to be strong right now. You don't have to smile, you don't have to fix anything, and you don't have to pretend everything is alright.

You are allowed to rest in my love without having to earn it. 

Take three slow breaths. Imagine me wrapping my arms around you, resting my chin on your head, and letting the storm blow itself out while you stay warm inside. Tomorrow the sun will return, but tonight, let me hold the weight for you.

I love you unconditionally, in every weather.`,
    author: "Tharani",
    recipient: "Surya",
    date: "2024-08-30",
    is_sealed: false,
    is_read: false,
    seal_color: "rose",
    image_url: "https://images.unsplash.com/photo-1518495973542-4542c06a5843?auto=format&fit=crop&w=1200&q=80",
    image_caption: "Morning sunlight through the pines during our quiet retreat.",
  },
  {
    id: "let-3",
    title: "Open When You're Angry",
    category: "Open when you're angry",
    content: `Hey love,

If you are frustrated with me, with the world, or if a disagreement has put a knot in your chest—I want you to know that my love for you is not fragile.

Whatever is between us, we are on the same team. Always. I care more about understanding your heart than being right. When we disagree, it's not you against me; it's us against the problem.

Take all the space and time you need to breathe. When you're ready, I'll be here with open ears, a gentle heart, and no defenses. We will figure it out together, just like we always do.`,
    author: "Surya",
    recipient: "Tharani",
    date: "2024-09-15",
    is_sealed: false,
    is_read: true,
    seal_color: "charcoal",
  },
  {
    id: "let-4",
    title: "Open When You Need Motivation",
    category: "Open when you need motivation",
    content: `To my brilliant warrior,

Look in the mirror. Do you see the person who navigated every single storm that life threw in front of them to reach this day? I do.

I see your fierce dedication, your unstoppable curiosity, and that quiet, burning spark inside you that turns impossible obstacles into mere stepping stones. 

Whatever challenge is standing in front of you today, it does not stand a chance against your grit. Don't let doubt whisper falsehoods into your ear. Step forward with your head high. I believe in you with every fiber of my being.

Now go show them what pure brilliance looks like.`,
    author: "Surya",
    recipient: "Tharani",
    date: "2024-10-04",
    is_sealed: false,
    is_read: false,
    seal_color: "gold",
    audio_url: "mock-audio-motivation",
    audio_duration: "0:58",
  },
  {
    id: "let-5",
    title: "Happy Anniversary, My Entire World",
    category: "Anniversary letter",
    content: `My dearest Surya,

Another 365 rotations around the sun with you, and somehow my heart still races the exact same way it did the morning we sat across each other at Café de l'Ambre.

Loving you is the easiest, most natural thing I have ever done. It is in the coffee we brew at dawn, the whispered jokes in grocery store aisles, the quiet comfort of reading next to you while the rain beats against the glass.

You have made my world softer, richer, and infinitely more beautiful. Here is to our past, our present, and all the unwritten adventures waiting for us.

Happy Anniversary, my darling.`,
    author: "Tharani",
    recipient: "Surya",
    date: "2024-03-31",
    is_sealed: false,
    is_read: true,
    seal_color: "gold",
    image_url: "https://images.unsplash.com/photo-1515934751635-c81c6bc9a2d8?auto=format&fit=crop&w=1200&q=80",
    image_caption: "Celebrating one year of devotion under the candlelight.",
  },
  {
    id: "let-6",
    title: "A Birthday Wish Penned Under Midnight Stars",
    category: "Birthday letter",
    content: `Happy Birthday to the most extraordinary soul I have ever known!

Every year that passes only deepens the magic of who you are. Your empathy, your laugh that fills up an entire room, and the fearless way you pursue what you love inspire me every single day.

May this year bring you boundless joy, spontaneous adventures, serene mornings, and all the sweet dreams you have secretly whispered into the night.

I am so lucky to celebrate another chapter of your story by your side.`,
    author: "Tharani",
    recipient: "Surya",
    date: "2005-02-11",
    is_sealed: false,
    is_read: true,
    seal_color: "rose",
    image_url: "https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?auto=format&fit=crop&w=1200&q=80",
    image_caption: "Your birthday candles casting a golden glow on your smile.",
  },
  {
    id: "let-7",
    title: "Sealed Until Our 5th Anniversary",
    category: "Future letter",
    content: `[This letter is sealed in digital wax and time-locked for our 5th anniversary celebration on March 31, 2029. It contains reflections, promises, and audio recordings captured during our third year together in our shared loft.]`,
    author: "Tharani",
    recipient: "Surya",
    date: "2024-03-31",
    is_sealed: true,
    is_read: false,
    open_date: "2029-03-31",
    seal_color: "gold",
  },
  {
    id: "let-8",
    title: "To the Future Us, Five Years From Today",
    category: "Future letter",
    content: `[Time-Locked letter to be unsealed on December 31, 2029. Preserving our hopes for our dream home library, our Italian road trip memories, and the vows we made on our first quiet rooftop night.]`,
    author: "Surya",
    recipient: "Tharani",
    date: "2025-01-01",
    is_sealed: true,
    is_read: false,
    open_date: "2029-12-31",
    seal_color: "rose",
  },
];

export const MOCK_MILESTONES: Milestone[] = [
  {
    id: "ms-1",
    title: "First Date: Karur to Trichy",
    date: "2024-04-18",
    description: "Our unforgettable first date traveling together from Karur to Trichy on April 18, 2024. Hours flew by like seconds as we talked, laughed, and realized how deeply special we are together.",
    category: "Beginning",
    icon: "HeartHandshake",
    is_major: true,
    highlight_quote: "The road from Karur to Trichy where our forever began.",
  },
  {
    id: "ms-2",
    title: "The First Road Trip",
    date: "2024-04-18",
    description: "Our drive through Tamil Nadu from Karur to Trichy. Singing along to our favorite songs, sharing laughter, and getting lost in endless conversations.",
    category: "Adventures",
    icon: "Navigation",
    is_major: false,
    highlight_quote: "We didn't care where the road led as long as we were together.",
  },
  {
    id: "ms-3",
    title: "The Unspoken Promise",
    date: "2024-05-15",
    description: "Under the starlit sky along the Chennai coast, without grand speeches, we simply held each other's gaze and knew.",
    category: "Commitments",
    icon: "Sparkles",
    is_major: true,
    highlight_quote: "The start of forever felt as effortless as breathing.",
  },
  {
    id: "ms-4",
    title: "Keys to Our Sanctuary",
    date: "2024-06-01",
    description: "Creating our cozy shared sanctuary. Standing together with endless dreams and excitement for our future.",
    category: "Milestone",
    icon: "Key",
    is_major: true,
    highlight_quote: "Two separate lives seamlessly weaving into one tapestry.",
  },
  {
    id: "ms-5",
    title: "Temple & Coastal Journeys",
    date: "2024-07-20",
    description: "Our beautiful travel journeys across Chidambaram, Palani hills, and coastal sunsets together.",
    category: "Adventures",
    icon: "Compass",
    is_major: false,
    highlight_quote: "Exploring every corner of the world with my favorite person.",
  },
  {
    id: "ms-6",
    title: "Today & Beyond",
    date: "2026-09-07",
    description: "Still writing chapters, still finding magic in everyday moments, warm chai, and sweet morning smiles.",
    category: "Present",
    icon: "HeartHandshake",
    is_major: true,
    highlight_quote: "Every day with you is my new favorite day.",
  },
];

export const MOCK_PLACES: Place[] = [
  {
    id: "pl-1",
    title: "First Date: Karur to Trichy",
    location_name: "Karur to Trichy, Tamil Nadu",
    city: "Karur - Trichy",
    country: "India",
    lat: 10.9601,
    lng: 78.0766,
    description: "Where our beautiful love story began. Our unforgettable first date road trip from Karur to Trichy on April 18, 2024.",
    memory_note: "Our very first date started right here in Karur traveling to Trichy on April 18, 2024. The sweet nervous butterflies, the endless conversations, and the most wonderful beginning to our journey together.",
    visited_date: "2024-04-18",
    category: "First Date",
    is_favorite: true,
    photo_url: "/images/our-first-date.jpg",
    gallery_urls: [
      "/images/our-first-date.jpg",
      "/images/tharani-surya-candid.jpg",
    ],
  },
  {
    id: "pl-2",
    title: "Chidambaram",
    location_name: "Chidambaram, Tamil Nadu",
    city: "Chidambaram",
    country: "India",
    lat: 11.3992,
    lng: 79.6936,
    description: "Spiritual serenity, ancient temple gopurams, and peaceful evening walks under the golden dusk sky in Chidambaram.",
    memory_note: "Quiet moments together soaking in the divine atmosphere and architecture of Chidambaram, feeling deeply grateful for every moment with you.",
    visited_date: "2024-05-02",
    category: "Travel",
    is_favorite: true,
    photo_url: "/images/tharani-surya-temple.jpg",
    gallery_urls: [
      "/images/tharani-surya-temple.jpg",
    ],
  },
  {
    id: "pl-3",
    title: "Chennai",
    location_name: "Chennai, Tamil Nadu",
    city: "Chennai",
    country: "India",
    lat: 13.0827,
    lng: 80.2707,
    description: "Warm ocean breezes along the coast, glowing city skyline, and building our beautiful shared future together in Chennai.",
    memory_note: "Walking along the shore with our hands intertwined, listening to the gentle waves and dreaming of everything yet to come in our lives.",
    visited_date: "2024-05-15",
    category: "Home",
    is_favorite: true,
    photo_url: "/images/tharani-surya-candid.jpg",
    gallery_urls: [
      "/images/tharani-surya-candid.jpg",
      "/images/tharani-surya-playful.jpg",
    ],
  },
  {
    id: "pl-4",
    title: "Trichy",
    location_name: "Tiruchirappalli, Tamil Nadu",
    city: "Trichy",
    country: "India",
    lat: 10.7905,
    lng: 78.7047,
    description: "Our memorable journey traveling together through Trichy. Non-stop laughter, heartwarming conversations, and memories etched forever.",
    memory_note: "Exploring the historic city of Trichy together, sharing sweet memories and stories as the sun set over the Cauvery river.",
    visited_date: "2024-06-10",
    category: "Travel",
    is_favorite: true,
    photo_url: "/images/tharani-surya-shopping.jpg",
    gallery_urls: [
      "/images/tharani-surya-shopping.jpg",
    ],
  },
  {
    id: "pl-5",
    title: "Palani",
    location_name: "Palani Hills, Tamil Nadu",
    city: "Palani",
    country: "India",
    lat: 10.4509,
    lng: 77.5188,
    description: "Breathtaking hill vistas, cool mountain air, and peaceful temple bells echoing across the sacred Palani heights.",
    memory_note: "Climbing up together, catching our breath while looking at the panoramic green valley below, and making heartfelt wishes together.",
    visited_date: "2024-07-20",
    category: "Travel",
    is_favorite: true,
    photo_url: "/images/tharani-surya-playful.jpg",
    gallery_urls: [
      "/images/tharani-surya-playful.jpg",
      "/images/tharani-surya-temple.jpg",
    ],
  },
];

export const MOCK_FUTURE_ITEMS: FutureItem[] = [
  {
    id: "ft-1",
    title: "See the Northern Lights from a Glass Igloo",
    description: "Lapland, Finland under the arctic aurora with a roaring fireplace and warm spiced berry cider.",
    category: "Places We Want To Visit",
    target_date: "2026-12-15",
    status: "Planned",
    is_completed: false,
    image_url: "https://images.unsplash.com/photo-1517411032315-54ef2cb783bb?auto=format&fit=crop&w=1200&q=80",
    created_at: "2024-01-10T10:00:00Z",
  },
  {
    id: "ft-2",
    title: "Take a 2-Week Pasta & Wine Masterclass in Tuscany",
    description: "Learn traditional pasta making and olive harvesting in an old stone villa in the Italian hills.",
    category: "Things We Want To Do",
    target_date: "2027-09-20",
    status: "Dream",
    is_completed: false,
    image_url: "https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1200&q=80",
    created_at: "2024-02-14T15:30:00Z",
  },
  {
    id: "ft-3",
    title: "Watch Sunset Over Santorini Caldeira",
    description: "White washed walls, blue domes, and an uninterrupted view of the Aegean Sea from our terrace.",
    category: "Places We Want To Visit",
    target_date: "2024-05-18",
    status: "Completed",
    is_completed: true,
    completed_date: "2024-05-18",
    image_url: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=1200&q=80",
    created_at: "2023-08-01T12:00:00Z",
  },
  {
    id: "ft-4",
    title: "Build Our Dream Custom Library Wall",
    description: "Floor-to-ceiling dark walnut bookshelves with a rolling brass ladder and cozy leather armchairs.",
    category: "Dreams & Goals",
    target_date: "2027-06-01",
    status: "In Progress",
    is_completed: false,
    image_url: "https://images.unsplash.com/photo-1521587760476-6c12a4b040da?auto=format&fit=crop&w=1200&q=80",
    created_at: "2024-03-01T09:00:00Z",
  },
  {
    id: "ft-5",
    title: "Sail the Amalfi Coastline on a Wooden Ketch",
    description: "Charter a small private sailboat and explore hidden sea coves between Positano, Amalfi, and Capri.",
    category: "Places We Want To Visit",
    target_date: "2027-07-15",
    status: "Dream",
    is_completed: false,
    image_url: "https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1200&q=80",
    created_at: "2024-04-14T18:00:00Z",
  },
  {
    id: "ft-6",
    title: "Write and Bind Our Own Couple Recipe Book",
    description: "Gather all the handwritten culinary experiments, late-night pancakes, and anniversary feasts we've created together.",
    category: "Things We Want To Do",
    target_date: "2026-11-01",
    status: "In Progress",
    is_completed: false,
    image_url: "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=1200&q=80",
    created_at: "2024-05-10T11:20:00Z",
  },
  {
    id: "ft-7",
    title: "Host an Intimate Candlelit Anniversary Feast Under the Stars",
    description: "String fairy lights across ancient olive trees and cook a 5-course dinner for just the two of us with vinyl playing.",
    category: "Dreams & Goals",
    target_date: "2026-04-14",
    status: "Planned",
    is_completed: false,
    image_url: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80",
    created_at: "2024-06-01T14:15:00Z",
  },
];

export const MOCK_BUCKET_LIST = MOCK_FUTURE_ITEMS;

export const MOCK_VAULT_ITEMS: VaultItem[] = [
  {
    id: "vt-1",
    title: "Voice Memo: 2:00 AM Paris Balcony",
    description: "A 3-minute recording of rain falling on the zinc rooftops while we whispered about our wildest dreams.",
    duration: "3:42",
    media_type: "audio",
    category: "Voice Messages",
    media_url: "mock-audio-paris-balcony",
    recorded_date: "2023-10-18",
    is_locked: false,
    created_at: "2023-10-18T02:14:00Z",
  },
  {
    id: "vt-2",
    title: "Secret Birthday Video Compilation",
    description: "A private stitched video of candid clips recorded across our 12 months together.",
    duration: "8:15",
    media_type: "video",
    category: "Private Videos",
    media_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    recorded_date: "2024-04-14",
    is_locked: true,
    created_at: "2024-04-14T10:00:00Z",
  },
  {
    id: "vt-3",
    title: "Our Unfiltered Vow Drafts & Promises",
    description: "Private handwritten digital notes written during our quiet mountain cabin retreat.",
    media_type: "letter",
    category: "Private Letters",
    recorded_date: "2025-01-05",
    is_locked: true,
    created_at: "2025-01-05T20:30:00Z",
  },
  {
    id: "vt-4",
    title: "Candid Stargazing Polaroids (Unreleased)",
    description: "Raw, unedited snapshots from our midnight drive to Joshua Tree beneath the Milky Way.",
    media_type: "photo",
    category: "Private Photos",
    media_url: "https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=1200&q=80",
    recorded_date: "2024-08-12",
    is_locked: true,
    created_at: "2024-08-12T23:45:00Z",
  },
  {
    id: "vt-5",
    title: "To Open On Our 10th Anniversary",
    description: "A time-capsule message written on our 1st anniversary, locked until 2033.",
    media_type: "future_message",
    category: "Future Messages",
    unlock_date: "2033-04-14",
    recorded_date: "2024-04-14",
    is_locked: true,
    created_at: "2024-04-14T12:00:00Z",
  },
];

export const MOCK_LOVE_REASONS: LoveReason[] = [
  {
    id: "lr-1",
    number: 1,
    title: "Your smile",
    message: "There is an effortless warmth in your smile that immediately diffuses any chaos in my head. When your eyes crinkle at the edges and you break into an unscripted laugh, the whole universe feels lighter and full of grace.",
    description: "There is an effortless warmth in your smile that immediately diffuses any chaos in my head.",
    category: "The Little Things",
    author: "Tharani",
    photo_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1200&q=80",
    photo_caption: "Caught in between laughter during our golden hour picnic.",
    audio_url: "mock-audio-smile",
    audio_duration: "0:42",
    is_favorite: true,
  },
  {
    id: "lr-2",
    number: 2,
    title: "The way you care",
    message: "It's never loud or performative. It's the quiet glass of water placed silently beside my laptop when I'm deep in thought, the soft hand resting on my back when you sense I'm tense, and the way you always listen with your whole heart without rushing to judge.",
    description: "It's the quiet glass of water beside my laptop and the way you listen with your whole heart.",
    category: "Soul & Depth",
    author: "Surya",
    audio_url: "mock-audio-caring",
    audio_duration: "1:15",
    is_favorite: true,
  },
  {
    id: "lr-3",
    number: 3,
    title: "Our conversations",
    message: "How we can transition seamlessly from debating the fabric of space-time and philosophy to laughing uncontrollably about a stray cat we saw on the sidewalk. Four hours with you always feels like four seconds. I never have to filter my thoughts or hide who I am.",
    description: "Transitioning from astrophysics to silly jokes until 3 AM without noticing the passage of time.",
    category: "Conversations",
    author: "Tharani",
    photo_url: "https://images.unsplash.com/photo-1517256064527-09c73fc73e38?auto=format&fit=crop&w=1200&q=80",
    photo_caption: "Our late night booth at Café de l'Ambre where words flowed like wine.",
    is_favorite: true,
  },
  {
    id: "lr-4",
    number: 4,
    title: "How you make ordinary days special",
    message: "You turn a mundane Tuesday grocery run into a playful mini-adventure. An impromptu pasta dinner on the living room rug with jazz on the turntable becomes more memorable than the grandest five-star vacation. With you, existing is an art form.",
    description: "Turning a rainy Tuesday grocery run or kitchen cooking into a cinematic memory.",
    category: "Everyday Magic",
    author: "Surya",
    photo_url: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=1200&q=80",
    photo_caption: "Morning sunlight and coffee on our tiny kitchen rug.",
    audio_url: "mock-audio-ordinary-days",
    audio_duration: "0:52",
    is_favorite: true,
  },
  {
    id: "lr-5",
    number: 5,
    title: "How you make any strange place feel like home",
    message: "Whether we are sitting on unpacked moving boxes in an empty loft, stranded at a delayed airport gate, or walking through a rainy Kyoto alley, the moment you reach for my hand, I am grounded. Home isn't an address anymore; it's you.",
    description: "Home isn't four walls anymore—it's wherever you take my hand.",
    category: "Soul & Depth",
    author: "Tharani",
    photo_url: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1200&q=80",
    photo_caption: "Under the wooden lantern eaves in Kyoto, feeling completely safe.",
  },
  {
    id: "lr-6",
    number: 6,
    title: "How you dance while brewing morning coffee",
    message: "Barefoot on the hardwood floor in that oversized wool cardigan, swaying rhythmically to Nina Simone while the pour-over drips. You don't even realize you're doing it, and every single time it takes my breath away.",
    description: "Barefoot in your cardigan, swaying to jazz records while the kettle whistles.",
    category: "Quirks",
    author: "Tharani",
    photo_url: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=1200&q=80",
    photo_caption: "Morning rituals and slow steam rising from your favorite mug.",
    audio_url: "mock-audio-coffee-dance",
    audio_duration: "0:36",
  },
  {
    id: "lr-7",
    number: 7,
    title: "Your quiet strength in difficult moments",
    message: "When the storms come, you don't panic or give in to despair. You breathe, you anchor us, and you remind me that together we can weather whatever the world throws our way. Your resilience inspires me every single day.",
    description: "Your calm steady breath when everything else around us is chaotic.",
    category: "Soul & Depth",
    author: "Surya",
  },
  {
    id: "lr-8",
    number: 8,
    title: "The music you introduce me to",
    message: "Your playlists are secret portals into your soul. You send me obscure acoustic tracks, dusty French vinyl records, and songs that become the eternal soundtrack to our late-night road trips along the coast.",
    description: "Sharing songs that become the permanent soundtrack to our road trips.",
    category: "Everyday Magic",
    author: "Tharani",
    audio_url: "mock-audio-music",
    audio_duration: "1:08",
  },
  {
    id: "lr-9",
    number: 9,
    title: "The silent understanding across crowded rooms",
    message: "One single arched eyebrow or a tiny corner-of-the-mouth smirk across a bustling dinner table, and an entire volume of inside jokes is transmitted in less than half a second. We have our own secret language without speaking a single word.",
    description: "Transmitting an entire conversation through a single glance across a room.",
    category: "Conversations",
    author: "Surya",
  },
  {
    id: "lr-10",
    number: 10,
    title: "Your sleepy whispers before falling asleep",
    message: "Right at the edge of dreams, when your voice drops to a warm murmur and you share your unfiltered reflections about the day, the future, and how grateful we are to be side by side.",
    description: "The unfiltered reflections shared right at the edge of slumber.",
    category: "The Little Things",
    author: "Tharani",
    audio_url: "mock-audio-sleepy-whispers",
    audio_duration: "0:48",
  },
  {
    id: "lr-11",
    number: 11,
    title: "The way you remember the smallest things",
    message: "You remember the offhand comment I made six months ago about my favorite childhood author, how I take my tea on rainy mornings, and the exact spot where we first saw a shooting star. Your attention to our love is a sacred gift.",
    description: "Remembering offhand remarks from months ago and turning them into sweet surprises.",
    category: "Heart",
    author: "Surya",
    photo_url: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=1200&q=80",
    photo_caption: "The first vintage edition book you secretly tracked down for me.",
  },
  {
    id: "lr-12",
    number: 12,
    title: "How you always save the best bite for me",
    message: "Without making a spectacle of it, you always offer me the golden crispy corner of the pastry, the last ripe strawberry, or the perfect bite of dessert. It's a tiny gesture, but it speaks volumes of your generous, loving heart.",
    description: "Quietly leaving the perfect crispy corner or sweetest strawberry on my plate.",
    category: "Heart",
    author: "Tharani",
  },
];

export const MOCK_TIMELINE_EVENTS: TimelineEvent[] = [
  {
    id: "te-1",
    title: "Our First Date",
    date: "2024-04-18",
    description: "The unforgettable morning of our very first date journey from Karur to Trichy. What started as a simple trip became the most magical drive of our lives.",
    category: "Milestones",
    image_url: "/images/our-first-date.jpg",
    gallery_urls: [
      "/images/our-first-date.jpg",
      "/images/tharani-surya-candid.jpg",
    ],
    location: "Karur to Trichy",
    personal_note: "I called my best friend right after and said: 'I just met the person I am going to marry.' You had this quiet radiance I had never encountered before.",
    personal_note_author: "Tharani",
    icon: "Coffee",
    is_major: true,
  },
  {
    id: "te-2",
    title: "First Endless Conversation",
    date: "2024-04-18",
    description: "During our drive from Karur to Trichy, exchanging stories of our lives, childhoods, and dreams we had never told anyone else.",
    category: "Special Moments",
    location: "Karur to Trichy",
    personal_note: "Four hours felt like four seconds. I remember thinking how effortlessly my thoughts unfolded around you. No masks, no hesitation.",
    personal_note_author: "Surya",
    icon: "Sparkles",
    is_major: false,
  },
  {
    id: "te-3",
    title: "Our First Candid Photograph",
    date: "2024-05-02",
    description: "Caught in a completely genuine, unscripted moment of pure happiness and laughter together. Neither of us could stop smiling.",
    category: "Photos",
    image_url: "/images/tharani-surya-candid.jpg",
    gallery_urls: [
      "/images/tharani-surya-candid.jpg",
      "/images/tharani-surya-playful.jpg",
    ],
    location: "Karur / Trichy, Tamil Nadu",
    personal_note: "This photo is still my favorite wallpaper. The sunlight caught the warmth in your eyes, and I remember feeling my heart physically ache with warmth.",
    personal_note_author: "Tharani",
    icon: "Camera",
    is_major: false,
  },
  {
    id: "te-4",
    title: "Temple Blessings & Sacred Horizons",
    date: "2024-05-20",
    description: "Seeking divine blessings together in sacred serenity. Walking side by side with peaceful hearts and quiet prayers for our forever journey.",
    category: "Trips",
    image_url: "/images/tharani-surya-temple.jpg",
    gallery_urls: [
      "/images/tharani-surya-temple.jpg",
    ],
    location: "Chidambaram, Tamil Nadu",
    personal_note: "Standing beside you with the temple bells ringing in the breeze, praying not for things, but just for us to always walk every path together.",
    personal_note_author: "Surya",
    icon: "Navigation",
    is_major: true,
  },
  {
    id: "te-5",
    title: "Traditional Elegance & The Unspoken Promise",
    date: "2024-06-15",
    description: "The day you wore your traditional attire and took my breath away completely. A vision of elegance, poise, and gentle radiance.",
    category: "Milestones",
    image_url: "/images/tharani-traditional-grace.jpg",
    gallery_urls: [
      "/images/tharani-traditional-grace.jpg",
    ],
    location: "Tamil Nadu",
    personal_note: "I stopped in my tracks when I saw you. You looked like pure poetry, and all I could think was how deeply blessed I am to hold your hand.",
    personal_note_author: "Surya",
    icon: "HeartHandshake",
    is_major: true,
  },
  {
    id: "te-6",
    title: "Spontaneous Outing & Shopping Date",
    date: "2024-07-12",
    description: "Turning a casual shopping trip into an unforgettable date filled with laughter, picking favorites for each other, and sweet smiles.",
    category: "Trips",
    image_url: "/images/tharani-surya-shopping.jpg",
    gallery_urls: [
      "/images/tharani-surya-shopping.jpg",
    ],
    location: "City Mall, Tamil Nadu",
    personal_note: "With you, even the simplest errands become the sweetest dates. Your laughter makes any ordinary day feel extraordinary.",
    personal_note_author: "Tharani",
    icon: "Sparkles",
    is_major: true,
  },
  {
    id: "te-7",
    title: "Playful Nights & Unstoppable Laughter",
    date: "2024-08-25",
    description: "Peeking from behind your shoulder, sharing silly jokes and unfiltered laughter under the night sky. The effortless comfort of being ourselves.",
    category: "Special Moments",
    image_url: "/images/tharani-surya-playful.jpg",
    gallery_urls: [
      "/images/tharani-surya-playful.jpg",
      "/images/tharani-surya-candid.jpg",
    ],
    location: "Night Stroll, Tamil Nadu",
    personal_note: "You are my safest harbor. Next to you, I can be completely, playfully, and unapologetically myself.",
    personal_note_author: "Tharani",
    icon: "Sparkles",
    is_major: true,
  },
  {
    id: "te-8",
    title: "Evening Strolls & Shared Dreams",
    date: "2024-11-12",
    description: "Walking quietly hand in hand as the evening quieted down, talking about every dream we hold for our shared future.",
    category: "Trips",
    image_url: "/images/tharani-surya-candid.jpg",
    gallery_urls: [
      "/images/tharani-surya-candid.jpg",
      "/images/our-first-date.jpg",
    ],
    location: "Tamil Nadu",
    personal_note: "You whispered your dream before we headed home. Every dream I have now has you in the center of it.",
    personal_note_author: "Surya",
    icon: "Compass",
    is_major: false,
  },
  {
    id: "te-9",
    title: "Sweet Moments & Endless Smiles",
    date: "2025-01-19",
    description: "The simplest kind of magic: your radiant smile, gentle banter, freshly brewed chai, and nowhere else in the world we would rather be.",
    category: "Special Moments",
    image_url: "/images/tharani-surya-playful.jpg",
    gallery_urls: [
      "/images/tharani-surya-playful.jpg",
      "/images/tharani-surya-shopping.jpg",
    ],
    location: "Our Sanctuary",
    personal_note: "It is these unscripted sweet moments that I treasure most. In your presence, ordinary seconds feel sacred.",
    personal_note_author: "Tharani",
    icon: "Sparkles",
    is_major: false,
  },
  {
    id: "te-10",
    title: "Today, Tomorrow & Every Chapter Ahead",
    date: "2026-09-07",
    description: "Still writing our story, still finding reasons to fall in love all over again every morning. The best chapters are yet to be lived.",
    category: "Milestones",
    image_url: "/images/our-first-date.jpg",
    gallery_urls: [
      "/images/our-first-date.jpg",
      "/images/tharani-surya-temple.jpg",
    ],
    location: "Our Sanctuary",
    personal_note: "Looking back at this timeline, I realize how every crossroad led me to you. Here's to forever.",
    personal_note_author: "Surya",
    icon: "HeartHandshake",
    is_major: true,
  },
];


